	CAUT	 Canadian Association of University Teachers
	ACPU	 Association Canadienne des Professeurs d'Universite'
-----------------------------------------------------------------------------
			294 rue Albert St., Suite 308, Ottawa, Ontario, K1P6E6
							phone:  (613) 237-6885
							fax:    (613) 237-2105


	Policy Statement on Academic Freedom
	------------------------------------

The common good of society depends upon the search for
knowledge and its free exposition.  Academic freedom in
universities is essential to both these purposes in the
teaching function of the university as well as in its
scholarship and research.  Academic staff shall not be
hindered or impeded in any way by the university or the
faculty association from exercising their legal rights
as citizens, nor shall they suffer any penalties because
of the exercise of such legal rights.  The parties agree
that they will not infringe or abridge the academic freedom
of any member of the academic community.  Academic members
of the community are entitled, regardless of prescribed
doctrine, to freedom in carrying out research and in
publishing the results thereof, freedom of teaching and
of discussion, freedom to criticize the university and
the faculty association, and freedom from institutional
censorship.  Academic freedom does not require neutrality
on the part of the individual.  Rather, academic freedom
makes commitment possible.  Academic freedom carries with
it the duty to use that freedom in a manner consistent
with the scholarly obligation to base research and teaching
on an honest search for knowledge.



Approved by the Council, May 1977

