The following is an online version of a flyer concerning the new 
Canadian laws on child pornography. Please note that the legal
situation in other countries, including the United States, varies
considerably.


Young People and Sex

What Can You Do?
What Can You Look At?
What Can You Read or Write About?


There is a lot of confusion about sex and young people. In Canada, the laws
don't make it easy to understand what you can and can't do. Many people
still believe the age of consent is 18 for straights and 21 for lesbians
and gays. But it isn't.

In 1988 the Criminal Code was changed to legislate different ages of
consent for different kinds of sex. 

In summer of 1993 the Criminal Code was changed again. Parliament passed
Bill C-128 (now Criminal Code section 163.1) which makes it illegal to
possess, produce, distribute or import what it calls "child pornography."
However, "child" and "pornography" don't mean what you think.

Many people may be surprised to learn that they now have illegal material
in their possession - among their books or videos or computer files.

This leaflet will try to make clear, as far as possible, the laws on sexual
words and pictures which involve young people, as well as the age of
consent laws. It is not intended to replace legal advice. The new law is a
radical departure from previous legal practise and may be unconstitutional.

But for now it is the law. If you have problems or concerns, see a lawyer.


So What's This New Porn Law?

     Criminal Code, section 163.1
     (1)  In this section, "child pornography" means

     (a) a photographic, film, video or other visual representation,
     whether or not it was made by electronic or mechanical means,
        (i) that shows a person who is or is depicted as being under the
     age of eighteen years and is engaged in or is depicted as engaged in
     explicit sexual activity, or
        (ii) the dominant characteristic of which is the depiction, for a
     sexual purpose, of a sexual organ or the anal region of a person under

     the age of eighteen years, or
     (b) any written material or visual representation that advocates or
     counsels sexual activity with a person under the age of eighteen years
     that would be an offense under this Act.


The new "child pornography" law forbids the production, circulation, or
possession of sexually explicit videos or pictures of any kind which depict
youths under 18 and those who look as though they are under 18. This is not
just sexual activity, but also showing the sexual organs or anal region
while posing for a sexual purpose.

The new law also outlaws written material or pictures that advocate or
counsel any illegal sexual activity with a person under 18.

You can see that this poses a number of problems. Who is to say if an
18-year-old looks younger? Is it now illegal to advocate changing the age
of consent laws? 

The new penalties are severe: 5 years for possession and 10 years for
production or circulation. And the old obscenity law (section 163) is still
in effect, banning the "undue exploitation of sex." You can be charged
under both the new and the old laws.

A lot of youth-oriented sexual material is on the borderline of the law,
and it is difficult to predict how the police and courts will react.
Consequently, you may have material in your home that you should destroy.

The following is a list of types of material that are most likely to
result in arrest and conviction, with the riskiest material listed first.
It is based on what has happened in other countries with such laws, and on
our suspicion (based on the statements of lawyers who testified at the
Parliamentary hearings) that the new law may be wholly or partly
unconstitutional. But this is only speculation. It may be that Canadian
courts will find that everything on this list is illegal.


1.  Pornographic images of those under 14

Moving or still pictures that use children in their production have been
ruled obscene by the Supreme Court of Canada. The new law bans possession
of these images (some other countries have already successfully banned
possession of sexual images of minors).


2.  Pornographic images of those 14-17

The producers and sellers of commercial porn, legally available in adult
video stores, take extreme care that the persons appearing in their videos
are all at least 18 years old. If a person mistakenly believed that the
actors in a porn movie were adults, the only defense would be to
demonstrate that all reasonable efforts had been taken to determine their
ages.

Many people now have home video recorders and make their own porn. Some of
them are sexually active teenagers who don't see themselves as children and
don't realize it is illegal to record what it is legal for them to do.


3.  Written material or visual images that defend, support or promote
illegal sexual activity involving those under 18

This applies only to activity that is illegal under the Criminal Code (see
Ages of Consent). So it is not illegal to defend relationships between
adults and teenagers 14 and over. But defending the right of teenagers to
have anal sex, even with the use of condoms, is now considered child
pornography.

Comments in Parliament indicated that this provision was intended to
criminalize both fiction and nonfiction that challenges age of consent laws
and other laws that restrict the rights or opportunities of sexually active
young people.

Some MPs specifically wanted to outlaw the publications of NAMBLA, the
North American Man-Boy Love Association.

This is a severe limitation of the right to political speech and its
constitutionality is open to question. Yet police in Toronto and Vancouver
have made it clear they intend to press charges anyway.

Gay booksellers, who are already the targets of special attention from
customs and police, have begun to remove from their shelves both written
porn and nonjudgmental written descriptions of inter-generational
relationships.


4.  Pornography involving adults (or imaginary characters!) who appear to
be younger than 18

And yes, comics, cartoons, or other drawings of imaginary characters who
look under 18 are just as illegal as images of real people.

It is hard to see how this aspect of the law can survive a charter
challenge, since the Supreme Court has said non-violent explicit sexual
material is generally accepted in Canada unless it uses children in its
production.

Nevertheless we expect that some commercially available porn will be
seized and some people will be prosecuted. Particularly vulnerable will be
material in which adults dress or act in a way that suggests they are
minors. The spoken word is not mentioned in the child porn law but the
interpretation of "depiction" could be stretched to include speech.


5.  Nonpornographic films, videos, pictures, or written fiction or
nonfiction with erotic depictions or discussions of sexual activity by
people under 18

Although the obvious targets of the new legislation are child and youth
porn and advocacy by groups such as NAMBLA, there is a great concern on the
part of writers, artists, film and video producers. The term "explicit
sexual activity" is undefined in Canadian law and could be used to
criminalize all manner of works dealing with youth sexuality.

Artistic merit or educational purpose can be used as a defense only after
a charge has been laid or material seized. Artistic merit is a debatable
quality at best, often recognized only late or posthumously, so it may not
be useful. In any case, the chilling effect of being labelled a child
pornographer will discourage many writers and artists from dealing with
young people's sexuality, even their own.

During hearings in Parliament, Bill C-128 was opposed by the Writers Guild
of Canada, the Canadian Civil Liberties Association, the ACTRA Performers
Guild, the Canadian Film and Television Production Association, the
National Association of Canadian Film & Video Distributors, the Canadian 
Broadcasting Corporation, the National Film Board, and the Canadian Bar 
Association.


What Will Happen Now?

When the Supreme Court ruled on obscenity in the 1992 Butler case, the
first convictions that followed were of lesbian and gay male material. One
month after the child porn law was proclaimed, the police arrested gay men
and young male prostitutes in Toronto. There is no reason to believe the
police and courts will suddenly become less homophobic or that serious
attempts will be made to educate and empower children in the area of sex or
encourage the autonomy of gay teens. No effective efforts are being made
to keep children safe from the bulk of the molestation they experience,
which occurs at the hands of family and relatives.

The legislation was rushed through during the dying hours of the last
parliament, with almost no opportunity for public scrutiny. The use of the
term "children" to include teenagers up to 18 years old indicates the
prevailing emotions. (The Young Offenders Act describes children as persons
who are or appear to be under the age of 12.)

The new law is poorly understood by many, including the MPs who voted for
it. It goes far beyond previous Canadian definitions of obscenity. But it
will take years for the courts to determine its constitutionality.

We urge everyone to become aware of the implications of the obscenity and
child pornography laws and to determine whether they are willing to go to
court to defend suspect material they may have in their possession.


------

The Ages of Consent  (Canadian Criminal Code, sections 150-159)

At any age, sex without consent is assault. Consent is not valid if
obtained through force, threats, fear, or lies about what is going to
happen. "Age of consent" laws go one step further and make sexual acts
illegal based simply on the age of the people involved, whether they
consent or not.

In Canada, the basic age of consent is 14. Anyone who is 14 or over can
consent to having most kinds of sex with anyone else who is 14 or over. But
there are some exceptions that allow or prohibit sexual activity below and
above that age.

At any age incest and bestiality are illegal. Incest is defined as sexual
intercourse with a family member who is a parent, child, brother, sister,
half-brother, half-sister, grandparent, or grandchild. Bestiality is sex
with animals.

Anal intercourse is only legal in a private place when only two people are
present and they are either married to each other or are both at least 18
years old.

It is illegal for anyone for a sexual purpose to expose their genitals to
a person under 14, to touch the young person directly or indirectly, or to
"invite, counsel, or incite" them to touch themselves or anyone else.

It is not illegal for a young person to sell sex, but it is only legal to
pay someone for sex if they are at least 18 years old. It is also illegal
to obtain, or attempt to obtain, sex with a person under 18 in exchange for
food, housing, money, drugs, etc.

When either person is in a position of trust or authority or in a relation
of dependence, the age of consent for sex or asking the young person to
engage in "sexual touching" is 18. This law applies to babysitters,
teachers, life guards, coaches, guardians, social workers, childcare
workers, etc., whether or not they are under 18 themselves.

People who are 14 or 15 can have sex with people under 14 who are no more
than two years younger (14-12, 15-13) as long as they are not in a position
of trust or authority.

People 12 or 13 years old can have sex with anyone without being charged
themselves unless they are in a position of trust or authority over their
partner. The Criminal Code does not apply to the actions of persons under
the age of 12.

But even though they have broken no criminal laws, sexually active young
people may still be taken into custody under provincial child welfare
legislation.

To avoid conviction, someone who mistakenly believes that a sexual partner
is over the legal age of consent would have to demonstrate that they took
"all reasonable steps" to know the age of the young person.

The maximum penalty for breaking the age of consent laws ranges from 5 to
14 years in prison. Repeated violations, whether or not the acts were
nonviolent and consensual, may result in a person's being classified as a
dangerous offender and imprisoned for life.


------

Some relevant quotations

"We think that it is essential to accept as a point of 
departure for policy-making, the idea that human beings enjoy 
and benefit from open and caring sexual relationships, 
characterized by mutuality and respect. This principle 
extends to those under 18 as well, for the child is, in our 
view, a sexual being. There was little support in the public 
hearings for repression of sexuality as a means of 
eliminating what people found offensive about pornography and 
prostitution. Rather, the submissions which addressed this 
issue stressed quite the opposite theme. It was pointed out, 
for example, that young people often turn to pornography, 
soft or hard core, in the search for information about their 
developing sexuality, because good sex education courses and 
healthy erotic literature, are unavailable to them. We often 
heard that one of the harms of pornography was the insult 
offered in such material to the joy and satisfaction of non-
exploitative sexual relationships. We were cautioned against 
developing a regime so strict that it would hamper the human 
need for sexual expression, whether in art, or particularly 
in the case of young people, in relations with consenting 
peers.

"We believe that all of these concerns have real merit."

- Report of the Special Committee on Pornography and 
Prostitution p 26, Paul Fraser, Q.C., Chairman  
February 1985


"Finally, explicit sex that is not violent and neither 
degrading nor dehumanizing is generally tolerated in our 
society and will not qualify as an undue exploitation of sex 
unless it employs children in its production."  

- Mr. Justice Sopinka, for the Supreme Court of Canada, 
obscenity trial of Donald Butler vs Her Majesty the Queen et al, 
February 27, 1992.

"...What is NAMBLA (North American Man-Boy Love Association) 
and what are its aims.  The following are direct quotes taken 
from the editorial page of the NAMBLA bulletin.  In my view 
it is critically important that we read them into the record 
to understand what the bill and the amendments which were 
worked out in committee do, and why.

"It says: 'We work to organize support for boys and men who 
have or desire consensual sexual and emotional relationships 
and to educate society on their positive nature. We speak out 
against the oppression endured by men and boys who love one 
another and support the right of all people to consensual 
intergenerational relationships.'

"It continues: 'NAMBLA condemns sexual abuse and all forms of 
coercion, but we insist there is a distinction between 
coercive and consensual sex.  Laws that focus only on the age 
of the participants fail to capture that distinction for they 
ignore the quality of the relationship.  Differences in age 
do not preclude mutual loving interaction between persons any 
more than differences in race or class.'

"What is the bottom line for NAMBLA? It advocates no age 
restriction whatsoever. Sex between a man and a tot, a young 
child, an infant, would be legal according to this insidious 
group."

- Tom Wappel, Member of Parliament (Scarborough West) 
House of Commons, June 15, 1993 

"And membership in the Rene Guyon Society or the North 
American Man-Boy Love Association is not required in order to 
question whether every instance of intergenerational  
sexuality is damaging.

"Ultimately, scientists, if no one else, must be objective in 
their approach to this emotional issue. Judgmental 
terminology regarding intergenerational sexuality is more 
dramatic than that in the earlier psychiatric literature on 
homosexuality. There, patients were labeled perverts and 
psychopaths. Here, the experience is always abuse, the 
children are invariably victims, the adults are perpetrators, 
and those who later report childhood sexual experiences are, 
without apology to victims of the Nazi Holocaust, survivors."

- Sexual Science and the Law, Richard Green, Harvard 
University Press, Cambridge, 1992

------

This document was produced by Forum 128 and funded by CLGRO 
(the Coalition for Lesbian and Gay Rights in Ontario.)

Forum 128 is a national research project into the Canadian 
sex panic and can be contacted via CLGRO, Box 822, Station A, 
Toronto M5W 1G3.

October 1993


