Xref: eff alt.sex:44168 alt.censorship:7027 alt.config:4859 alt.comp.acad-freedom.talk:4462 soc.women:21491
Newsgroups: alt.sex.bondage,alt.sex,alt.censorship,alt.config,alt.comp.acad-freedom.talk,soc.women
Path: eff!widener!ukma!darwin.sura.net!mips!zaphod.mps.ohio-state.edu!uwm.edu!ux1.cso.uiuc.edu!m.cs.uiuc.edu!herodotus.cs.uiuc.edu!kadie
From: kadie@herodotus.cs.uiuc.edu (Carl M. Kadie)
Subject: Canadian obscenity law (was Re: Congratulations!)
Message-ID: <1992May29.191336.1843@m.cs.uiuc.edu>
Keywords: by the way, I don't appreciate the "Followup-to: " games, Rob
Sender: news@m.cs.uiuc.edu (News Database (admin-Mike Schwager))
Organization: University of Illinois, Dept. of Comp. Sci., Urbana, IL
References: <1992May27.231014.17907@cc.umontreal.ca> <1992May28.010057.18609@cs.sfu.ca> <15423@autodesk.COM> <1992May28.211907.19985@cs.sfu.ca> <rdippold.707162004@cancun>
Date: Fri, 29 May 1992 19:13:36 GMT
Lines: 41

The current issue of _Ms._ magazine (p. 14, May/June 1992y) has details
of Canada's new definition of obscenity.

In a decision given in Feburary, Justice John Sopinka of the Canadian
Supreme Court wrote: "If true equality between male and female persons
is to be achived we cannot ignore the threat to equality resulting
from exposure to audiences of certain types of violent and degrading
material."

The article says:
[...]  'The case provided the court with the opportunity to claify the
weak and muddled obscenity law, which was based on "undue exploitation
of sex", which was based on "undue exploitation of sex" violating
undefined "community standards." The court's more precise defintions
of these therms no longer include morality and taste,. But violence
and degradation will invariable push pornography over the line into
illegal obscenity: "The portrayal of sex coupled with violence will
almost always consitute the undue exploitation of sex," said the court
in its rulling. "Explicit sex which is degrading or dehumanizing may
be undue if the risk of harm is substantial."
[...]
'[T]he guidelines are now clear: degradation, bondage, child
pornography, and violence are out; adult erotica, no matter how
explicit, will not be considered obscene.'

According to the _Ms._ article: "The ruling has the support of most
women's groups in Canada, where the free-speech tradition is not a
dominant as it is in the U.S.; as a result, feminist debate on
pornorgaphy is less intense." Also: "'This is of world historic
importance,' proclaimed Catherine A. MacKinnon, the University of
Michigan law professor whose analysis of pornography and the law,
co-authored with writer Andrea Dworkin, helped form the basis of
LEAF's [Woman's Legal Education and Acuation Fund] argument.

This is article is followed by one critizing Ireland's paternalistic
abortion law. On p. 74 the is an article critizing arts censorship in
the U.S.

- Carl
--
Carl Kadie -- kadie@cs.uiuc.edu -- University of Illinois at Urbana-Champaign
