[The current version of this document is at 
http://www.ffly.com/****/Lite/PoliciesOut.html, as of Jan. 1997. The "****"
is part of the URL, it is not a typo.]

                          Firefly Community Policy
                  COMMUNITY . ENTERTAINMENT . INFORMATION
        The space where you can freely exchange ideas and opinions.
                                      
   There is intense debate surrounding issues of privacy and freedom of
   speech on the Internet. We believe that all of our members should have
   their privacy respected and have the ability to freely express
   themselves within the firefly community.

   Below is an outline of our mutual expectations within firefly
   Online. No community is perfect but every thriving community should be
   full of voices: so please contribute, debate, express yourself, and if
   there is anything that we can do to make your experience better -
   don't hesitate to speak up about that too!
   
   Trust and Privacy
   
   Trust and privacy are of paramount importance within the firefly
   community and we have implemented the following policies:
   
   We DO NOT REQUIRE your actual name and address.
   
   Your e-mail and/or firefly address WILL NOT BE DISCLOSED unless you
   tell us to do so.
   
   We WILL NOT RETAIN on-line conversational transcripts conducted
   between our members. We do however retain transcripts of chats that
   have been scheduled and publicized as special events on firefly.
   
   We WILL NOT READ OR RELEASE firefly mail exchanged between firefly
   members.
   
   Feel Free To Express Yourself
   
   firefly is all about its community. All members are actively
   encouraged to freely express themselves by submitting reviews,
   participating in chat and bulletin boards, sending firefly mail,
   writing articles and creating personal home pages.
   
   We respect copyrights and other intellectual property rights
   and expect our members to do so as well. Please be sure that you have
   the distribution rights to the information and images you post in the
   firefly community.
 
   Comments and contributions from members should be consistent
   with firefly community values and comply with applicable laws.

   Our policy is to neither edit nor remove member contributions
   because of their content. Exceptions to this policy may arise,
   however, if contributions violate applicable laws or the standards
   developed by the members of the firefly community.
   
   Ratings and Recommendations
   
   Your recommendations are generated by firefly and are COMPLETELY
   IMPARTIAL. Recommendations depend solely on your tastes and the tastes
   of the community at large, never those of our advertisers or or
   business partners.
   
   To ensure that these ratings and recommendations remain
   unbiased we will not edit or in any way modify recommendations
   generated by the system and its members.
   
   Advertising and Data

   As a free service, firefly depends on advertising and sponsorship for
   its revenue. Advertising will be clearly delineated as such.
   
   Individual information collected by firefly will only be used
   to provide personalized content, recommendations, and advertising. We
   do reserve the right to use the information in aggregate form (e.g.
   advertiser reports show percent male and percent female that click
   through).

   Advertisers are prohibited from contributing ratings to the
   system and leaving reviews in areas designated for member
   contributions. If it is brought to our attention that any reviews have
   been written by employees or representatives of advertisers, those
   reviews will be removed from firefly.

   Advertisers understand that these policies - and the
   maintenance of our integrity in general - is in their best interests.
   We are proud of the firefly Community Policy and are committed to
   respecting your privacy.
   
   Looking forward to meeting you on firefly,
   
   Tori Hackett
   General Manager
   firefly Online
   
     _________________________________________________________________
                                      
   Copyright 1996, Firefly Network, Inc.
   

 ******************************************************************


[The current version of this document is at
http://www.firefly.com/Lite/Registration.phtml#Terms as of Jan. 1997.]
   
   
          Joining firefly puts you directly in touch with entertainment
          and people you'd like, based on your tastes and preferences.
          
          Membership is absolutely free and the information you provide
          below [i.e. in the membership form] will only be used to offer 
          you information and experiences based on you. This information 
          will never be disclosed to anyone without your explicit prior 
          consent.
          
          We're committed to building a thriving community based on
          trust, privacy and freedom of expression; please read more
          about the firefly Community Policy.
          
[membership form omitted]

   firefly Terms of Service
   
   By joining and using firefly, you agree to use firefly according to
   these Terms of Service as outlined below.
   
   FEEL FREE TO EXPRESS YOURSELF
   
   Comments and contributions from members should be consistent with
   firefly community values and comply with applicable laws. Since we
   cannot prevent members from placing inappropriate or illegal content
   on firefly, we can only remove such content once we have been made
   aware of its existence. We do reserve the right to remove material
   brought to our attention that violates applicable laws. We can also
   block a member's access to the site if we receive documented
   complaints about the member's contributions and communications on
   firefly. The information, advice, facts, opinions or other content
   appearing on firefly that are posted by members or third parties are
   those of the respective authors and do not reflect our views. We do
   not assume responsibility or liability for these materials.
   
   COPYRIGHTED INFORMATION
   
   By contributing to firefly, you represent that you have all of the
   necessary rights to the use of the materials, communications, or other
   information that you have provided to or displayed on firefly. Because
   we are committed to promoting user content and sharing the works of
   the firefly community outside firefly online, you automatically grant
   us or acknowledge that the owner of these items grants us the
   royalty-free, irrevocable right to copy and re-use the items in any
   form, media, or technology now known or hereafter developed, in any
   manner that we see fit.
   
   FIREFLY NETWORK, INC. RESERVES THE RIGHT TO CHANGE THE POLICIES SET
   FORTH HEREIN AND IN THE FIREFLY COMMUNITY POLICY, WHICH ARE SUBJECT TO
   THESE TERMS OF SERVICE, AT ANY TIME AND SHALL NOT INCUR ANY LIABILITY
   AS A RESULT OF A FAILURE OF ANY THIRD PARTY TO ADHERE TO SUCH
   POLICIES. USERS WILL BE NOTIFIED IN THE EVENT OF A CHANGE IN THE
   FIREFLY COMMUNITY POLICY. IN ADDITION, UNDER NO CIRCUMSTANCES SHALL
   FIREFLY NETWORK, INC. HAVE ANY LIABILITY WHATSOEVER FOR ANY DAMAGES,
   DIRECT, INDIRECT, OR CONSEQUENTIAL, IN CONNECTION WITH YOUR USE OF THE
   SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND
   REGARDLESS OF THE CAUSE OF ACTION UNDER WHICH SUCH DAMAGES ARE SOUGHT,
   INCLUDING, WITHOUT LIMITATION, BREACH OF CONTRACT, NEGLIGENCE OR OTHER
   TORT. FIREFLY NETWORK, INC. DISCLAIMS ANY AND ALL WARRANTIES
   HEREUNDER, INCLUDING WITHOUT LIMITATION, ALL IMPLIED WARRANTIES OF
   MERCHANTABILITY, TITLE, AND FITNESS FOR A PARTICULAR PURPOSE.

        Copyright 1995, 1996 Firefly Network, Inc Patent Pending
